#include<iostream>
using namespace std;

const double pi = 3.14;

// 设计一个圆类，求圆的周长
// 公式：2*pi*半径 

//class 代表设计一个类，类后面紧跟的就是类的名称
 
class Circle
{
	//访问权限
public:

//属性
//半径
	int m_r;

//行为
//获取圆的周长(函数)

	double claculateZC()
	{
		return 2 * pi * m_r;
	}

};


int main()
{
	//通过圆类，创建具体的圆（对象）
	Circle c1;
	//给圆的对象 属性进行赋值
	c1.m_r = 10;
	cout << "圆的周长为：" << c1.claculateZC() << endl;


	system("pause");
	return 0;

}


实例
#include<iostream>
using namespace std;
#include<string>


class student 
{
public:

//属性
	string  m_Name;//姓名
	int m_Id;//学号

	//行为
	//显示学号姓名
	void showStudent()
	{
		cout << "姓名：" << m_Name <<  "学号：" << m_Id << endl;
	
	}
};

int main()
{
	//创建具体学生
	student s1;
	s1.m_Name = "张三";
	s1.m_Id = 1911518899;
	s1.showStudent();

	system("pause");
	return 0;

}


权限

#include<iostream>
using namespace std;
#include<string>

//访问权限
//公共权限 public  成员 类内可以访问 类外可以访问

//保护权限 protected  成员 类内可以访问 类外不可以访问

//私有权限 private  成员 类内可以访问 类外不可以访问

class Person 
{
public:

//属性
	string  m_Name;//姓名
protected:
	string m_car;

private:
	int m_password;


public:
	void func()
	{
		m_Name = "张三";
		m_car = "拖拉机";
		m_password = 123456;
	}
};

int main()
{
	//创建具体学生
	Person p1;
	
	p1.m_Name = "李四";

	system("pause");
	return 0;

}
