#include<iostream>
using namespace std;

const double pi = 3.14;

// 设计一个圆类，求圆的周长
// 公式：2*pi*半径 

//class 代表设计一个类，类后面紧跟的就是类的名称
 
class Circle
{
	//访问权限
public:

//属性
//半径
	int m_r;

//行为
//获取圆的周长(函数)

	double claculateZC()
	{
		return 2 * pi * m_r;
	}

};


int main()
{
	//通过圆类，创建具体的圆（对象）
	Circle c1;
	//给圆的对象 属性进行赋值
	c1.m_r = 10;
	cout << "圆的周长为：" << c1.claculateZC() << endl;


	system("pause");
	return 0;

}
